import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AlertAndLoaderProvider,useAlertAndLoader } from "@/context/AlertAndLoaderContext/AlertAndLoaderContext";
import { AuthProvider } from "@/context/AuthContext/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AlertAndLoaderProvider>
          <AuthProvider>
        {children}
        </AuthProvider>
        </AlertAndLoaderProvider>
      </body>
    </html>
  );
}

export { useAlertAndLoader };
